stages:
  - test
  - build

test:
  image: plangora/alpine-elixir-phoenix:otp-23.2.3-elixir-1.11.3
  services:
    - postgres:latest
  variables:
    MIX_ENV: "test"
    DB_HOST: postgres
    POSTGRES_DB: transigo_admin_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  script:
    - mix clean
    - mix do deps.get, test --exclude skip

build:
  stage: build
  environment: production
  only:
    - master
  image: docker:19.03
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH/prod:$CI_COMMIT_SHORT_SHA
  services:
    - docker:19.03-dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build --tag $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE